### ISSUE TITLE
Can't install agora-python-sdk through method 1

### ISSUE THREAD

**Issue by Synoecium** [AgoraIO-Community/Agora-Python-SDK#2]
Platform: Windows 7-64
Python 3.8.7
pip 21.0.1

$ pip3 install agora-python-sdk
Collecting agora-python-sdk
  Using cached agora_python_sdk-3.1.2.1-cp38-cp38-win_amd64.whl (9.3 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/99/93/ef6763b898c084cc963077bf23456744c0023cb51f38fdf9a97b86db8194/agora_python_sdk-3.1.2.1-cp38-cp38-win_amd64.whl#sha256=74679dd3294c6dd36c8bd4e5052bfc9534e1f66901938fc35e9d017bd57a8a71 (from https://pypi.org/simple/agora-python-sdk/) (requires-python:>=3.6). Requested agora-python-sdk from https://files.pythonhosted.org/packages/99/93/ef6763b898c084cc963077bf23456744c0023cb51f38fdf9a97b86db8194/agora_python_sdk-3.1.2.1-cp38-cp38-win_amd64.whl#sha256=74679dd3294c6dd36c8bd4e5052bfc9534e1f66901938fc35e9d017bd57a8a71 has inconsistent version: filename has '3.1.2.1', but metadata has '3.1.2'
ERROR: Could not find a version that satisfies the requirement agora-python-sdk
ERROR: No matching distribution found for agora-python-sdk

**Comment by haroldao** [comment]
> Platform: Windows 7-64
> Python 3.8.7
> pip 21.0.1
> 
> $ pip3 install agora-python-sdk
> Collecting agora-python-sdk
> Using cached agora_python_sdk-3.1.2.1-cp38-cp38-win_amd64.whl (9.3 MB)
> WARNING: Discarding https://files.pythonhosted.org/packages/99/93/ef6763b898c084cc963077bf23456744c0023cb51f38fdf9a97b86db8194/agora_python_sdk-3.1.2.1-cp38-cp38-win_amd64.whl#sha256=74679dd3294c6dd36c8bd4e5052bfc9534e1f66901938fc35e9d017bd57a8a71 (from https://pypi.org/simple/agora-python-sdk/) (requires-python:>=3.6). Requested agora-python-sdk from https://files.pythonhosted.org/packages/99/93/ef6763b898c084cc963077bf23456744c0023cb51f38fdf9a97b86db8194/agora_python_sdk-3.1.2.1-cp38-cp38-win_amd64.whl#sha256=74679dd3294c6dd36c8bd4e5052bfc9534e1f66901938fc35e9d017bd57a8a71 has inconsistent version: filename has '3.1.2.1', but metadata has '3.1.2'
> ERROR: Could not find a version that satisfies the requirement agora-python-sdk
> ERROR: No matching distribution found for agora-python-sdk

Same issue
![image](https://user-images.githubusercontent.com/36776278/108452684-2e5e5a00-7269-11eb-9803-0a6822968d3f.png)

**Comment by YiqingJackieHuang** [comment]
@Synoecium @haroldao This problem was caused by our update on PyPI to support py39. It has been fixed right now, please have a second try by using the same command. Sorry for the inconvenience.

**Comment by Synoecium** [comment]
I cloned repository again, tried the same commanad and have the same issue.

**Comment by YiqingJackieHuang** [comment]
> I cloned repository again, tried the same commanad and have the same issue.

What about `pip install --no-cache-dir agora-python-sdk==3.1.2`?

By the way, when installing our package via PyPI, there is nothing to do with the source code in this repo because our distribution packages on PyPI have already been compiled for each platform.

**Comment by Synoecium** [comment]
> By the way, when installing our package via PyPI, there is nothing to do with the source codes in this repo because our distribution packages on PyPI have already been compiled for each platform.

Sorry, i tried the method 2 installation but failed too, so i thought its matter to launch pip install from source dir.
In any case, the new command isn't work for me:
$ pip install --no-cache-dir agora-python-sdk==3.1.2
ERROR: Could not find a version that satisfies the requirement agora-python-sdk==3.1.2
ERROR: No matching distribution found for agora-python-sdk==3.1.2

**Comment by haroldao** [comment]
> @Synoecium @haroldao This problem was caused by our update on PyPI to support py39. It has been fixed right now, please have a second try by using the same command. Sorry for the inconvenience.

nope... still doesn't work ... /:

**Comment by haroldao** [comment]
> > By the way, when installing our package via PyPI, there is nothing to do with the source codes in this repo because our distribution packages on PyPI have already been compiled for each platform.
> 
> Sorry, i tried the method 2 installation but failed too, so i thought its matter to launch pip install from source dir.
> In any case, the new command isn't work for me:
> $ pip install --no-cache-dir agora-python-sdk==3.1.2
> ERROR: Could not find a version that satisfies the requirement agora-python-sdk==3.1.2
> ERROR: No matching distribution found for agora-python-sdk==3.1.2

same...

**Comment by spherebread** [comment]
Python update to 3.9.2 helps, guys

**Comment by YiqingJackieHuang** [comment]
@haroldao @Synoecium I have just updated all distribution packages on PyPI to `agora_python_sdk==3.1.2.2`. Please have a try with `pip install --no-cache-dir agora-python-sdk==3.1.2.2`.

**Comment by Synoecium** [comment]
Now this command works, thank you.

**Comment by haroldao** [comment]
> Now this command works, thank you.

![image](https://user-images.githubusercontent.com/36776278/108610540-98e0d880-73d6-11eb-88b3-676f4245fcb8.png)
Same 😋🔥
