### ISSUE TITLE
Support for AudioFrameObserver

### ISSUE THREAD

**Issue by Saeki-M** [AgoraIO-Community/Agora-Python-SDK#5]
The VideoFrameObserver is supported for real time image processing, but is there a way to process the audio in real time?

**Comment by YiqingJackieHuang** [comment]
The related API called [`pullAudioFrame`](https://docs.agora.io/en/Video/API%20Reference/cpp/v3.1.2/classagora_1_1media_1_1_i_media_engine.html#aaf43fc265eb4707bb59f1bf0cbe01940) has not been implemented for *Python* at this point. Sorry for the inconvenience!

By the way, I wonder how urgent is your requirement to process real-time audio raw data?

**Comment by YiqingJackieHuang** [comment]
We are in the process of adding `AudioFrameObserver` to *Python SDK*.

**Comment by Saeki-M** [comment]
Great News!
I am trying to do real time audio processing, and would like the audio stream.

**Comment by YiqingJackieHuang** [comment]
@Saeki-M @wchr-aun @50Bytes-dev
AudioFrameObserver has been supported. Please re-install the SDK via `pip uninstall agora-python-sdk && pip install agora-python-sdk==3.1.2.10`.
